### ISSUE TITLE
rs_recordNotebookError when using inside R notebook

### ISSUE THREAD

**Issue by frederikziebell** [lindeloev/job#4]
Create an .Rmd with the following content (without the #s) and run the code chunk.

```
# ```{r}
# job::job({1+1})
# ```
```

The result is an error 
```
Error in .Call("rs_recordNotebookError", err) : 
  C symbol name "rs_recordNotebookError" not in load table
Calls: sourceWithProgress ... <Anonymous> -> .rs.recordTraceback -> errorReporter -> .Call
Execution halted
```

I like the interacive way of using R markdown code chunks for data analysis, so it would be good to have `job::job()` be working there.

**Comment by lindeloev** [comment]
Should be fixed now. Can you run `remotes::install_github("lindeloev/job")` and try again to confirm?

It seems that RMarkdown sets `option()$error` to a function which references objects not found in the job environment. The fact that `job::job({1+1), opts = NULL)` works was my lead into this.

**Comment by frederikziebell** [comment]
I still get the same error. Already checked that the `b34f2dc` commit is installed and `job::job({1+1), opts = NULL)` works for me. If it's relevant, I'm on a Mac.

**Comment by lindeloev** [comment]
OK, it's still tractable then! Could you run this in the console:

    console_opts = options()

And this in your notebook chunk:

    chunk_opts = options()

Then somewhere:

    dplyr::setdiff(names(console_opts), names(chunk_opts))

Then let me know the output from the last line. And try looking up what is stored in those options in `console_opts`?

**Comment by frederikziebell** [comment]
This gives a `character(0)`. The only difference between the two options is that `chunk_opts` contains an additional `"dplyr.tibble.print"`.

**Comment by lindeloev** [comment]
Tried uploading a new version. Could you try that out?

Turns out that `error` is language - not a function. `waldo::compare()` also came in handy to detect a few other options that were set in the chunk.

BTW, just learned that order matters here. Running stuff in the chunk actually sets global options for the rest of the session.

**Comment by frederikziebell** [comment]
Now I get `Error in job::job({ : object 'chunk_opts' not found` 🙈

**Comment by lindeloev** [comment]
OMG, thanks for responding so fast! A reminder for me to ALWAYS run unit tests before committing. Should work now?

**Comment by frederikziebell** [comment]
Still same error in 9c60578

**Comment by lindeloev** [comment]
OK, I managed to kill a similar bug in #10. Could you check if that also closes this issue, @frederikziebell?

**Comment by lindeloev** [comment]
I'm pretty sure this bug was fixed so I'm closing now. Please re-open if it persists.
